# yaml-language-server: $schema= https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  nerdFontsVersion: "3"
  showNumstatInFilesView: true
  showDivergenceFromBaseBranch: arrowAndNumber
  fileTreeSortCaseSensitive: false

  spinner:
    rate: 83
    frames: ['', '', '', '', '', '']
  language: "en"
  branchColorPatterns:
    '(?i)^bugfix([/_-]|$)': red
    '(?i)^feature([/_-]|$)': green
    '(?i)^project([/_-]|$)': blue
    '(?i)^develop$': magenta
    '(?i)^release([/_-]|$)': cyan
    '(?i)^(master|main)$': yellow
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - reverse
  customIcons:
    extensions:
      ".http":
        icon: "\U000F109B"
        color: '#5050FF'
notARepository: prompt
git:
  autoFetch: true
os:
  editPreset: vscode